### PR TITLE
Add missing dlfcn.h include in global_libpython_loader.cpp

### PR DESCRIPTION
**Pull request by Cogitri**
This fixes the build on musl libc.

### CODE REVIEW

**Comment by Cogitri** [comment]
We're using this in Alpine Linux right now, not quite sure if we need to make this conditional to only be included on non glibc.

**Comment by thp** [comment]
Hm, if you look at the diff context, that include is already in there (the next non-empty line after the line you inserted). This change has already been merged in #100, which is included from version 1.5.5 onwards. I didn't see which version Alpine has, but maybe you tried building an older version?

**Comment by Cogitri** [comment]
Ah yes, my bad, didn't see something newer than 1.5.4 was released already.thanks

**Comment by Cogitri** [comment]
Yup, works fine with 1.5.8, sorry for the noise

**Pull request closed without merging**
